apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mongodb-svc.yaml
  - mongodb-ss.yaml  # DO NOT add `mongodb-init.js` here

labels:
  - includeSelectors: true
    pairs:
      app: mongodb
      project: proj-gke

configMapGenerator:
  - name: mongodb-init-colordb
    files:
      - mongodb-init.js  # Corrected relative path (it must be in `_base`)
