apiVersion: apps/v1
kind: Deployment
metadata:
  name: color-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: color-api
  template:
    metadata:
      labels:
        app: color-api
    spec:
      containers:
      - name: color-api
        image: lmacademy/color-api:2.0.0
        env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: mongodb-colordb-creds
                key: USERNAME
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongodb-colordb-creds
                key: PASSWORD
          - name: DB_URL
            value: "mongodb://$(DB_USER):$(DB_PASSWORD)@mongodb-ss-0.mongodb-svc:27017/color-db"
        ports:
          - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
